'use strict';
const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
const fs = require('node:fs/promises');

(async () => {
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
  const executablePath = process.env.CDG_PACKAGED_EXECUTABLE;
  const app = await electron.launch({ ...(executablePath ? { executablePath } : {}),
    args: executablePath ? ['--smoke-test'] : [path.resolve(__dirname, '..'), '--smoke-test'], env, timeout: 60000 });
  try {
    const page = await app.firstWindow();
    await page.waitForFunction(() => document.getElementById('system-timezone').textContent !== '—');
    assert.equal(await page.title(), 'Claude Desktop Guard');
    assert.equal(await page.locator('#proxy-url').inputValue(), '');
    assert.equal(await page.locator('#start-button').isDisabled(), true);
    assert.equal(await page.locator('#probe-button').isDisabled(), true);
    assert.equal(await page.locator('#route-mode').inputValue(), 'proxy');
    await page.locator('#route-mode').selectOption('amnezia');
    assert.equal(await page.locator('#proxy-options').isHidden(), true);
    assert.equal(await page.locator('#amnezia-options').isVisible(), true);
    assert.equal(await page.locator('#mihomo-options').isHidden(), true);
    assert.equal(await page.locator('#vpn-interface').inputValue(), '');
    assert.equal(await page.locator('#probe-button').isDisabled(), true);
    assert.equal(await page.locator('#start-button').isDisabled(), true);
    assert.match(await page.locator('#amnezia-hint').textContent(), /Только IPv4/);
    await page.locator('#route-mode').selectOption('proxy');
    await page.locator('#proxy-url').fill('http://127.0.0.1:1');
    assert.equal(await page.locator('#probe-button').isEnabled(), true);
    assert.equal(await page.locator('#start-button').isDisabled(), true);
    assert.equal(await page.locator('#client-mask-enabled').isChecked(), false);
    assert.equal(await page.locator('#client-mask-options').isHidden(), true);
    await page.locator('#client-mask-enabled').check();
    assert.equal(await page.locator('#client-mask-options').isVisible(), true);
    assert.equal(await page.locator('#probe-button').isEnabled(), true, 'Exit check must work before completing client profile');
    await page.locator('#mask-timezone').fill('UTC;touch /tmp/x');
    assert.equal(await page.locator('#mask-timezone').getAttribute('aria-invalid'), 'true');
    await page.locator('#mask-timezone').fill('UTC');
    await page.locator('#mask-language').fill('en-US;evil');
    assert.equal(await page.locator('#mask-language').getAttribute('aria-invalid'), 'true');
    await page.locator('#mask-language').fill('en-GB');
    await page.locator('#mask-region').fill('DE');
    assert.equal(await page.locator('#probe-button').isEnabled(), true);
    assert.equal(await page.locator('#mask-copy-button').isDisabled(), true);
    const fixtureState = await page.evaluate(() => window.guard.snapshot());
    const routeIdentity = await page.evaluate(() => identity(input().profile));
    const checkedProbe = { ip: '8.8.8.8', country: 'FI', timezone: 'Europe/Helsinki', observedAt: new Date().toISOString(), routingIdentity: routeIdentity };
    await page.evaluate(value => render(value), { ...fixtureState, probe: checkedProbe });
    assert.equal(await page.locator('#mask-timezone').inputValue(), 'UTC', 'Exit must not silently change requested timezone');
    assert.equal(await page.locator('#mask-region').inputValue(), 'DE', 'Exit must not silently change requested country');
    await page.locator('#mask-copy-button').click();
    assert.equal(await page.locator('#mask-timezone').inputValue(), 'Europe/Helsinki');
    assert.equal(await page.locator('#mask-region').inputValue(), 'FI');
    assert.equal(await page.locator('#mask-language').inputValue(), 'en-GB', 'Copy button must not infer language from country');
    const applied = { requested: { timezone: 'Europe/Helsinki', language: 'en-GB', region: 'FI' }, status: 'applied', measured: null };
    await page.evaluate(value => render(value), { ...fixtureState, probe: checkedProbe, clientMask: applied });
    assert.equal(await page.locator('#requested-language').textContent(), 'en-GB');
    assert.match(await page.locator('#client-mask-status').textContent(), /переданы; значения внутри Claude автоматически не измеряются/);
    await page.evaluate(value => render(value), { ...fixtureState, clientMask: { ...applied, nativeLocaleApplied: false } });
    assert.match(await page.locator('#client-mask-status').textContent(), /регион ОС Windows сохранены/);
    await page.evaluate(value => render(value), { ...fixtureState, probe: { ...checkedProbe, timezone: 'UTC' }, gate: { healthy: true, country: 'FI', timezone: 'Europe/Helsinki' }, clientMask: { ...applied, measured: { timezone: 'Europe/Helsinki', language: 'en-GB', region: 'FI' } } });
    assert.equal(await page.locator('#exit-timezone').textContent(), 'Europe/Helsinki');
    assert.match(await page.locator('#client-mask-status').textContent(), /Измерено внутри приложения/);
    await page.evaluate(value => render(value), fixtureState);
    await page.locator('#client-mask-enabled').uncheck();
    assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
    assert.equal(await page.evaluate(() => typeof window.process), 'undefined');
    await page.locator('#proxy-url').fill('');
    const screenshot = process.env.CDG_SCREENSHOT || path.join(os.tmpdir(), 'claude-desktop-guard.png');
    await fs.mkdir(path.dirname(screenshot), { recursive: true });
    await page.screenshot({ path: screenshot, fullPage: true });
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
    assert.equal(overflow, false, 'UI must fit window width');
    console.log('Electron UI smoke passed: explicit route/interface/client parameters, safe validation, manual copy, applied vs measured, renderer isolation, layout.');
  } finally { await app.close(); }
})().catch(error => { console.error(error.message); process.exitCode = 1; });
